name: nominatim_flutter
description: The Nominatim Flutter Plugin facilitates seamless interactions with the Nominatim service for reverse geocoding and place searches in Flutter apps. It boasts asynchronous data loading via a separate isolate and efficient caching with Hive.
version: 0.0.2
homepage: https://github.com/binhlam10796/nominatim_flutter

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  dio_cache_interceptor: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test:
  mockito:
