name: nominatim_flutter
description: The Nominatim Flutter Plugin enables smooth Nominatim service integration for reverse geocoding and place searches in Flutter, with async loading and Hive caching.
version: 0.0.3
homepage: https://github.com/binhlam10796/nominatim_flutter

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  dio_cache_interceptor: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: